/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Utils.Utils;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Henrique
 */
public class Books extends javax.swing.JFrame {
    
    public Books() {
        initComponents();
        
        if(Utils.profile != 5) {
            UsersMenuItem.setVisible(false);
            InsertButton.setVisible(false);
            ModifySingleButton.setVisible(false);
            ModifyAllButton.setVisible(false);
            DeleteButton.setVisible(false);
            
            BooksTable.getColumnModel().getColumn(0).setMinWidth(0);
            BooksTable.getColumnModel().getColumn(0).setMaxWidth(0);
            BooksTable.getColumnModel().getColumn(0).setWidth(0);
        }
        
        ResultSet result = Utils.SelectAllRegistry("books");
        
        try {
            while(result.next()) {
                int id = result.getInt("id");
                String isbn = result.getString("isbn");
                String title = result.getString("title");
                String author = result.getString("author");
                String publisher = result.getString("publisher");
                int year = result.getInt("year");
                String obs = result.getString("obs");
                boolean borrowed = result.getBoolean("borrowed");
                
                Object[] data = {id, isbn, title, author, publisher, year, obs};
                
                if(!borrowed) ((DefaultTableModel)BooksTable.getModel()).addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Books.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        PanelHolder = new javax.swing.JPanel();
        TableScrollPanel = new javax.swing.JScrollPane();
        BooksTable = new javax.swing.JTable();
        OperationsToolBar = new javax.swing.JToolBar();
        InsertButton = new javax.swing.JButton();
        ModifyAllButton = new javax.swing.JButton();
        ModifySingleButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BorrowButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        WindowMenu = new javax.swing.JMenu();
        BooksMenuItem = new javax.swing.JMenuItem();
        UsersMenuItem = new javax.swing.JMenuItem();
        BorrowsMenuItem = new javax.swing.JMenuItem();
        UserMenu = new javax.swing.JMenu();
        EditMenuItem = new javax.swing.JMenuItem();
        LogOutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BooksTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "ISBN", "Title", "Author", "Publisher", "Year", "Observations"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BooksTable.setIntercellSpacing(new java.awt.Dimension(0, 5));
        BooksTable.setRowHeight(30);
        BooksTable.getTableHeader().setReorderingAllowed(false);
        TableScrollPanel.setViewportView(BooksTable);

        OperationsToolBar.setFloatable(false);
        OperationsToolBar.setFocusable(false);

        InsertButton.setText("Insert new book");
        InsertButton.setFocusable(false);
        InsertButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InsertButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });
        OperationsToolBar.add(InsertButton);

        ModifyAllButton.setText("Modify all");
        ModifyAllButton.setToolTipText("Modifies the whole row");
        ModifyAllButton.setFocusable(false);
        ModifyAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModifyAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModifyAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyAllButtonActionPerformed(evt);
            }
        });
        OperationsToolBar.add(ModifyAllButton);

        ModifySingleButton.setText("Modify single");
        ModifySingleButton.setToolTipText("Modifies selection");
        ModifySingleButton.setFocusable(false);
        ModifySingleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModifySingleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModifySingleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifySingleButtonActionPerformed(evt);
            }
        });
        OperationsToolBar.add(ModifySingleButton);

        DeleteButton.setText("Delete");
        DeleteButton.setFocusable(false);
        DeleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        OperationsToolBar.add(DeleteButton);

        BorrowButton.setText("Borrow");
        BorrowButton.setFocusable(false);
        BorrowButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BorrowButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowButtonActionPerformed(evt);
            }
        });
        OperationsToolBar.add(BorrowButton);

        javax.swing.GroupLayout PanelHolderLayout = new javax.swing.GroupLayout(PanelHolder);
        PanelHolder.setLayout(PanelHolderLayout);
        PanelHolderLayout.setHorizontalGroup(
            PanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addComponent(OperationsToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelHolderLayout.setVerticalGroup(
            PanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OperationsToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );

        WindowMenu.setText("Window");

        BooksMenuItem.setText("Books");
        WindowMenu.add(BooksMenuItem);

        UsersMenuItem.setText("Users");
        UsersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersMenuItemActionPerformed(evt);
            }
        });
        WindowMenu.add(UsersMenuItem);

        BorrowsMenuItem.setText("Borrows");
        BorrowsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowsMenuItemActionPerformed(evt);
            }
        });
        WindowMenu.add(BorrowsMenuItem);

        MenuBar.add(WindowMenu);

        UserMenu.setText("User");

        EditMenuItem.setText("Edit");
        EditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMenuItemActionPerformed(evt);
            }
        });
        UserMenu.add(EditMenuItem);

        LogOutMenuItem.setText("Log out");
        LogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuItemActionPerformed(evt);
            }
        });
        UserMenu.add(LogOutMenuItem);

        MenuBar.add(UserMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuItemActionPerformed
        Utils.OpenNewWindow(new Login(), this);
    }//GEN-LAST:event_LogOutMenuItemActionPerformed

    private void ModifyAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyAllButtonActionPerformed
        int row = BooksTable.getSelectedRow();
        
        if(row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a cell", "No cell selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String id = BooksTable.getValueAt(row, 0).toString();
        String isbn = (String) BooksTable.getValueAt(row, 1);
        String title = (String) BooksTable.getValueAt(row, 2);
        String author = (String) BooksTable.getValueAt(row, 3);
        String publisher = (String) BooksTable.getValueAt(row, 4);
        String year = BooksTable.getValueAt(row, 5).toString();
        String obs = (String) BooksTable.getValueAt(row, 6);
        
        String[] data = {id, isbn, title, author, publisher, year, obs};
          
        Utils.OpenNewWindow(new UpdateBook(data), this);
    }//GEN-LAST:event_ModifyAllButtonActionPerformed

    private void ModifySingleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifySingleButtonActionPerformed
        
        int row = BooksTable.getSelectedRow();
        int column = BooksTable.getSelectedColumn();
        
        if(row == -1 || column == -1) {
            JOptionPane.showMessageDialog(null, "Please select a cell!", "No cell selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int id = Integer.parseInt(BooksTable.getValueAt(row, 0).toString());
        String name = BooksTable.getColumnName(column);
        
        if(column == 0) {
            JOptionPane.showMessageDialog(null, "You cannot modify the id column!", "ID column selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String value = (String) JOptionPane.showInputDialog(null, "Enter the book " + name, "Modify " + name, 1, null, null, BooksTable.getValueAt(row, column));
        
        if(!value.equals("")) {
            if(name.equals("Year")) {
                try {
                    Integer.parseInt(value);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "'" + value + "' in field, it's not a number", "Not a number", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            if(Utils.UpdateSingleRegistry(id, "books", name.toLowerCase(), value)) {
                BooksTable.setValueAt(value, row, column);
                JOptionPane.showMessageDialog(null, "Registry updated successfully!", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The field cannot be empty!", "Field is empty", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModifySingleButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int row = BooksTable.getSelectedRow();
        
        if(row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a cell!", "No cell selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int safe = JOptionPane.showConfirmDialog(null, "Are you sure you want do delete the registry?", "Confirm deletion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        //If clicked yes, delete
        if(safe == 0) {
            Utils.DeleteRegistry((int)BooksTable.getValueAt(row, 0), "books");
            
            ((DefaultTableModel)BooksTable.getModel()).removeRow(row);
            JOptionPane.showMessageDialog(null, "Registry successfully deleted!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        Utils.OpenNewWindow(new InsertBook(), this);
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void UsersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersMenuItemActionPerformed
        Utils.OpenNewWindow(new Users(), this);
    }//GEN-LAST:event_UsersMenuItemActionPerformed

    private void BorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowButtonActionPerformed
        int row = BooksTable.getSelectedRow();
        
        if(row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a cell!", "No cell selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int id = Integer.parseInt(BooksTable.getValueAt(row, 0).toString());
        
        if(Utils.BorrowBook(id)) {
            ((DefaultTableModel)BooksTable.getModel()).removeRow(row);
            
            JOptionPane.showMessageDialog(null, "Book successfully borrowed", "Book borrowed", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BorrowButtonActionPerformed

    private void BorrowsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowsMenuItemActionPerformed
        Utils.OpenNewWindow(new Borrows(), this);
    }//GEN-LAST:event_BorrowsMenuItemActionPerformed

    private void EditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMenuItemActionPerformed
        Utils.OpenNewWindow(new ModifyUser(), this);
    }//GEN-LAST:event_EditMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BooksMenuItem;
    private javax.swing.JTable BooksTable;
    private javax.swing.JButton BorrowButton;
    private javax.swing.JMenuItem BorrowsMenuItem;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JMenuItem EditMenuItem;
    private javax.swing.JButton InsertButton;
    private javax.swing.JMenuItem LogOutMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton ModifyAllButton;
    private javax.swing.JButton ModifySingleButton;
    private javax.swing.JToolBar OperationsToolBar;
    private javax.swing.JPanel PanelHolder;
    private javax.swing.JScrollPane TableScrollPanel;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JMenuItem UsersMenuItem;
    private javax.swing.JMenu WindowMenu;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
