CREATE DATABASE Biblioteca;

USE Biblioteca;

CREATE TABLE books
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	isbn VARCHAR(20) NOT NULL,
	title VARCHAR(50) NOT NULL,
	author VARCHAR(50) NOT NULL,
	publisher VARCHAR(50) NOT NULL,
	year INT NOT NULL,
	observations VARCHAR(350),
	borrowed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE users
(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    profile INT NOT NULL
);

CREATE TABLE borrows
(
	id INT PRIMARY KEY AUTO_INCREMENT,
    id_book INT NOT NULL,
	id_user INT NOT NULL,
	date_borrow DATETIME NOT NULL DEFAULT NOW(),
	date_devolution DATETIME NOT NULL DEFAULT (NOW() + INTERVAL 7 DAY),
	date_effective DATETIME,
    is_returned BOOLEAN DEFAULT FALSE
);
