/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Books;

import Utils.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor Henrique
 */
public class InsertBook extends javax.swing.JFrame {

    /**
     * Creates new form Insert
     */
    public InsertBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertPanel = new javax.swing.JPanel();
        InsertLabel = new javax.swing.JLabel();
        ISBNLabel = new javax.swing.JLabel();
        ISBNTextField = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        TitleTextField = new javax.swing.JTextField();
        AuthorLabel = new javax.swing.JLabel();
        AuthorTextField = new javax.swing.JTextField();
        PublisherLabel = new javax.swing.JLabel();
        PublisherTextField = new javax.swing.JTextField();
        YearLabel = new javax.swing.JLabel();
        YearTextField = new javax.swing.JTextField();
        ObsLabel = new javax.swing.JLabel();
        ObsScrollPane = new javax.swing.JScrollPane();
        ObsTextArea = new javax.swing.JTextArea();
        ApplyButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsertLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InsertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InsertLabel.setText("Insert new book");

        ISBNLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ISBNLabel.setText("ISBN");

        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TitleLabel.setText("Title");

        AuthorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AuthorLabel.setText("Author");

        PublisherLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PublisherLabel.setText("Publisher");

        YearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        YearLabel.setText("Year");

        ObsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ObsLabel.setText("Observations");

        ObsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ObsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ObsTextArea.setColumns(20);
        ObsTextArea.setRows(5);
        ObsScrollPane.setViewportView(ObsTextArea);

        ApplyButton.setText("Apply");
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertPanelLayout = new javax.swing.GroupLayout(InsertPanel);
        InsertPanel.setLayout(InsertPanelLayout);
        InsertPanelLayout.setHorizontalGroup(
            InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertPanelLayout.createSequentialGroup()
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(ApplyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ISBNLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TitleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AuthorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PublisherLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(YearLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ISBNTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(AuthorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PublisherTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(YearTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TitleTextField)))
                    .addGroup(InsertPanelLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(ObsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ObsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InsertLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        InsertPanelLayout.setVerticalGroup(
            InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertPanelLayout.createSequentialGroup()
                .addComponent(InsertLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ISBNLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AuthorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PublisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublisherLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertPanelLayout.createSequentialGroup()
                        .addComponent(ObsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InsertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApplyButton)
                            .addComponent(CancelButton)))
                    .addComponent(ObsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        Utils.OpenNewWindow(new Books(), this);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
        
        String isbn = ISBNTextField.getText();
        String title = TitleTextField.getText();
        String author = AuthorTextField.getText();
        String publisher = PublisherTextField.getText();
        String year = YearTextField.getText();
        String obs = ObsTextArea.getText();

        String[] data = {isbn, title, author, publisher, year, obs};
        
        if(isbn.equals("") || title.equals("") || author.equals("") || publisher.equals("") || year.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields", "All fields are required", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Integer.parseInt(year);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "'" + year + "' in field year, it's not a number", "Not a number", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(Utils.InsertNewBookRegistry(data)) {
            JOptionPane.showMessageDialog(null, "Registry inserted successfully!", "", JOptionPane.INFORMATION_MESSAGE);
            
            Utils.OpenNewWindow(new Books(), this);
        } else {
            JOptionPane.showMessageDialog(null, "There was an error!", "", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ApplyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JLabel AuthorLabel;
    private javax.swing.JTextField AuthorTextField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ISBNLabel;
    private javax.swing.JTextField ISBNTextField;
    private javax.swing.JLabel InsertLabel;
    private javax.swing.JPanel InsertPanel;
    private javax.swing.JLabel ObsLabel;
    private javax.swing.JScrollPane ObsScrollPane;
    private javax.swing.JTextArea ObsTextArea;
    private javax.swing.JLabel PublisherLabel;
    private javax.swing.JTextField PublisherTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JTextField YearTextField;
    // End of variables declaration//GEN-END:variables
}
